Feature/pg
vilevchak/TaskManager pull request #4
Opened 2023-01-10 18:50 UTC by vilevchak

2023-01-10 23:05 UTC, aleksandr-semenov-dbp requested changes
Папки `__pycache__` не должно быть в репозитории. Она вообще не должна появляться если все инструменты использовать внутри докера

2023-01-15 22:25 UTC, aleksandr-semenov-dbp requested changes

2023-01-15 22:25 UTC, aleksandr-semenov-dbp commented on Dockerfile
> +RUN curl -sSL curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/901bdf0491005f1b3db41947d0d938da6838ecb9/get-poetry.py > get-poetry.py \
Здесь что-то не то, слишком много curl

2023-01-16 17:23 UTC, vilevchak commented on Dockerfile
> +RUN curl -sSL curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/901bdf0491005f1b3db41947d0d938da6838ecb9/get-poetry.py > get-poetry.py \
Старая ссылка увы перестала работать с 01.01.2023. Сейчас уже исправил наверное на более подходящее решение.

2023-01-18 08:45 UTC, aleksandr-semenov-dbp approved these changes

2023-01-18 08:57 UTC, merged